# This is a basic workflow to help you get started with Actions

name: Github Page Automatic Deploy Action
# This action Build and deploy the app to branch gh-pages (Github Pages)
# Author: Germán Aliprandi <galiprandi@gmail.com>

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Git user
        run: |
          git config --local user.name  ${{ github.actor }}
          git config --local user.email "galiprandi@gmail.com"

      - name: Installing dependencies
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploy
        with:
          build-dir: dist
        uses: NickSchimek/deploy_jamstack_action@main
